openapi: '3.1.0'
info:
  title: Faro Collector API
  version: 1.0.0
paths:
  /collect/{appKey}:
    post:
      parameters:
        - name: appKey
          description: |
            The application key is provided by your endpoint provider.
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payload'
      summary: Submit a Faro payload
      responses:
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
        '202':
          description: OK
components:
  schemas:
    Event:
      type: object
      required: [name, domain, timestamp]
      properties:
        name:
          type: string
        domain:
          type: string
        attributes:
          type: object
          
          additionalProperties:
            type: string
        timestamp:
          type: string
          format: date-time
    Log:
      type: object
      required: [message, level, timestamp]
      properties:
        message:
          type: string
        level:
          type: string
        context:
          type: object
          additionalProperties:
            type: string
        timestamp:
          type: string
          format: date-time
        trace:
          type: object
          required: [trace_id, span_id]
          properties:
            trace_id:
              type: string
            span_id:
              type: string
    StackFrame:
      type: object
      properties:
        colno:
          type: integer
        filename:
          type: string
        function:
          type: string
        in_app:
          type: boolean
        lineno:
          type: integer
    Exception:
      type: object
      required: [type, value, timestamp]
      properties:
        type:
          type: string
        value:
          type: string
        stacktrace:
          type: array
          items:
            $ref: '#/components/schemas/StackFrame'
          
          minItems: 0
        timestamp:
          type: string
          format: date-time
        trace:
          type: object
          
          properties:
            trace_id:
              type: string
            span_id:
              type: string
        context:
          type: object
          
          additionalProperties:
            type: string
    Measurement:
      type: object
      required: [values, type, timestamp]
      properties:
        values:
          type: object
          json: omitempty
          additionalProperties:
            type: number
        type:
          type: string
        timestamp:
          type: string
          format: date-time
        trace:
          type: object
          properties:
            trace_id:
              type: string
            span_id:
              type: string
        context:
          type: object
          additionalProperties:
            type: string
    SpanEvent:
      type: object
      required: [name]
      properties:
        attributes:
          type: array
        droppedAttributesCount:
          type: integer
        name:
          type: string
        timeUnixNano:
          type: string
    SdkMeta:
      type: object
      required: [name, version]
      properties:
        name:
          type: string
        version:
          type: string
    AppMeta:
      type: object
      required: [name, release, version, environment]
      properties:
        name:
          type: string
        release:
          type: string
        version:
          type: string
        environment:
          type: string
    UserMeta:
      type: object
      properties:
        username:
          type: string
        id:
          type: string
        email:
          type: string
        attributes:
          type: object
          additionalProperties:
            type: string
    SessionMeta:
      type: object
      properties:
        id:
          type: string
        attributes:
          type: object
          additionalProperties:
            type: string
    PageMeta:
      type: object
      properties:
        url:
          type: string
    BrowserMeta:
      type: object
      properties:
        name:
          type: string
        version:
          type: string
        os:
          type: string
        mobile:
          type: boolean
    Payload:
      type: object
      required: [meta]
      properties:
        events:
          type: array
          items:
            $ref: '#/components/schemas/Event'
          minItems: 0
        logs:
          type: array
          items:
            $ref: '#/components/schemas/Log'
          minItems: 0
        exceptions:
          type: array
          items:
            $ref: '#/components/schemas/Exception'
          minItems: 0
        measurements:
          type: array
          items:
            $ref: '#/components/schemas/Measurement'
        meta:
          type: object
          properties:
            sdk:
              $ref: '#/components/schemas/SdkMeta'
            app:
              $ref: '#/components/schemas/AppMeta'
            user:
              $ref: '#/components/schemas/UserMeta'
            session:
              $ref: '#/components/schemas/SessionMeta'
            page:
              $ref: '#/components/schemas/PageMeta'
            browser:
              $ref: '#/components/schemas/BrowserMeta'
            view:
              type: object
              properties:
                name:
                  type: string
        traces:
          type: object
          properties:
            resourceSpans:
              type: array
              items:
                type: object
                required: [resource, instrumentationLibrarySpans]
                properties:
                  resource:
                    type: object
                    properties:
                      attributes:
                        type: object
                        required: [key, value]
                        properties:
                          key:
                            type: string
                          value:
                            type: object
                            additionalProperties:
                              type: string
                  instrumentationLibrarySpans:
                    type: array
                    items:
                      type: object
                      required: [instrumentationLibrary]
                      properties:
                        instrumentationLibrary:
                          type: object
                          required: [name, version]
                          properties:
                            name:
                              type: string
                            version:
                              type: string
                        spans:
                          type: array
                          items:
                            type: object
                            required: [kind, name, spanId, startTimeUnixNano, endTimeUnixNano, status, traceId]
                            properties:
                              attributes:
                                type: object
                                required: [key, value]
                                properties:
                                  key:
                                    type: string
                                  value:
                                    type: object
                                    oneof:
                                      - properties:
                                          stringValue:
                                            type: string
                                      - properties:
                                          intValue:
                                            type: integer
                              droppedAttributesCount:
                                type: integer
                              droppedEventsCount:
                                type: integer
                              droppedLinksCount:
                                type: integer
                              endTimeUnixNano:
                                type: integer
                              events:
                                type: array
                                items:
                                  $ref: '#/components/schemas/SpanEvent'
                              kind:
                                type: integer
                                enum:
                                  - 1
                              links:
                                type: array
                                items:
                                  type: object
                                  additionalProperties:
                                    type: string
                              name:
                                type: string
                              parentSpanId:
                                type: string
                              spanId:
                                type: string
                              startTimeUnixNano:
                                type: integer
                              status:
                                type: object
                                properties:
                                  code:
                                    type: integer
                                  message:
                                    type: string
                              traceId:
                                type: string

