// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

module github.com/open-telemetry/opentelemetry-collector-releases/contrib

go 1.22

require (
	go.opentelemetry.io/collector/confmap/provider/envprovider v1.25.0
	go.opentelemetry.io/collector/confmap/provider/fileprovider v1.25.0
	go.opentelemetry.io/collector/confmap/provider/httpprovider v1.25.0
	go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.25.0
	go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.25.0
	github.com/grafana/faro/pkg/receiver/faro b99ea3b24d33279048e17fb910cfba668992122c
	go.opentelemetry.io/collector/exporter/debugexporter v0.119.0
	github.com/grafana/faro/pkg/exporter/faroexporter b99ea3b24d33279048e17fb910cfba668992122c
	go.opentelemetry.io/collector/otelcol v0.119.0
)

require (
	github.com/knadh/koanf/maps v0.1.1 // indirect
	github.com/knadh/koanf/providers/confmap v0.1.0 // indirect
)








